{
 "title": "Server",
 "tags": [ "Linux" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "集群",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values({job=\"$node\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"$node\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"$node\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU核心数量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{job=\"$node\",instance=\"$instance\",mode=\"system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",job=\"$node\",instance=\"$instance\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total{job=\"$node\",instance=\"$instance\"}[1m])) by (instance) * 100",
     "legendFormat": "CPU总利用率"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\",job=\"$node\",instance=\"$instance\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total{job=\"$node\",instance=\"$instance\"}[1m])) by (instance) * 100",
     "legendFormat": "系统"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\",job=\"$node\",instance=\"$instance\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total{job=\"$node\",instance=\"$instance\"}[1m])) by (instance) * 10",
     "legendFormat": "用户"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"iowait\",job=\"$node\",instance=\"$instance\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total{job=\"$node\",instance=\"$instance\"}[1m])) by (instance) * 10",
     "legendFormat": "IO阻塞"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"steal\",job=\"$node\",instance=\"$instance\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total{job=\"$node\",instance=\"$instance\"}[1m])) by (instance) * 10",
     "legendFormat": "虚拟化"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"irq\",job=\"$node\",instance=\"$instance\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total{job=\"$node\",instance=\"$instance\"}[1m])) by (instance) * 10",
     "legendFormat": "硬件中断"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"softirq\",job=\"$node\",instance=\"$instance\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total{job=\"$node\",instance=\"$instance\"}[1m])) by (instance) * 10",
     "legendFormat": "软件中断"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"nice\",job=\"$node\",instance=\"$instance\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total{job=\"$node\",instance=\"$instance\"}[1m])) by (instance) * 10",
     "legendFormat": "低优先级任务"
    }
   ]
  },
  {
   "title": "内存",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"$node\",instance=\"$instance\"}- node_memory_MemAvailable_bytes{job=\"$node\",instance=\"$instance\"} )\n/ node_memory_MemTotal_bytes{job=\"$node\",instance=\"$instance\"} * 100",
     "legendFormat": "内存利用率"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$node\",instance=\"$instance\"}",
     "legendFormat": "内存总量"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"$node\",instance=\"$instance\"}",
     "legendFormat": "可用内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$node\",instance=\"$instance\"}-node_memory_MemAvailable_bytes{job=\"$node\",instance=\"$instance\"}",
     "legendFormat": "已用内存"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"$node\",instance=\"$instance\"}",
     "legendFormat": "空闲内存"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"$node\",instance=\"$instance\"}",
     "legendFormat": "缓冲区内存"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"$node\",instance=\"$instance\"}",
     "legendFormat": "缓存内存"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$node\", instance=\"$instance\"}",
     "legendFormat": "内存总量"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",job=\"$node\",instance=\"$instance\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total{job=\"$node\",instance=\"$instance\"}[1m])) by (instance) * 100",
     "legendFormat": "CPU总利用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"$node\",instance=\"$instance\"} / (node_memory_MemTotal_bytes{job=\"$node\",instance=\"$instance\"})))* 100",
     "legendFormat": "内存总利用率"
    }
   ]
  },
  {
   "title": "负载",
   "type": "timeseries",
   "description": "uptime",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_load1{job=\"$node\"}",
     "legendFormat": "1min"
    },
    {
     "expr": "node_load5{job=\"$node\"}",
     "legendFormat": "5min"
    },
    {
     "expr": "node_load15{job=\"$node\"}",
     "legendFormat": "15min"
    }
   ]
  },
  {
   "title": "磁盘读写速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{job=\"$node\"}[1m]))",
     "legendFormat": "总读速率"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{job=\"$node\"}[1m]))",
     "legendFormat": "总写速率"
    },
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"$node\"}[1m])",
     "legendFormat": "{{device}}读"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"$node\"}[1m])",
     "legendFormat": "{{device}}写"
    }
   ]
  },
  {
   "title": "功耗和温度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(node_hwmon_power_watt{job=\"$node\", instance=\"$instance\"})",
     "legendFormat": "总功耗"
    },
    {
     "expr": "node_hwmon_temp_celsius{job=\"$node\"}",
     "legendFormat": "{{chip}}"
    }
   ]
  },
  {
   "title": "网络速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{job=\"$node\",instance=\"$instance\"}[1m])) by (instance) / 1024",
     "legendFormat": "上行"
    },
    {
     "expr": "sum by(instance) (rate(node_network_receive_bytes_total{job=\"$node\",instance=\"$instance\"}[1m])) / 1024",
     "legendFormat": "下行"
    }
   ]
  },
  {
   "title": "网络Socket连接信息",
   "type": "timeseries",
   "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数\n\nUDP_inuse - 正在使用的 UDP 套接字数量\n\nRetransSegs - TCP 重传报文数\n\nOutSegs - TCP 发送的报文数\n\nInSegs - TCP 接收的报文数",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=\"$node\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=\"$node\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{job=\"$node\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{job=\"$node\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{job=\"$node\"}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "irate(node_netstat_Tcp_InSegs{job=\"$node\"}[5m])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_OutSegs{job=\"$node\"}[5m])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "irate(node_netstat_Tcp_RetransSegs{job=\"$node\"}[5m])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  }
 ]
}